name: Build and test server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: master

      - name: "Go to server directory"
        run: cd server

      - name: Build
        run: zig build test
