name: Publish packages
on:
  push:
    branches:
      - master
jobs:
  publish-plugin-postcss:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        working-directory: modules/plugin-postcss
        run: bunx jsr add @lush/lush && bun install
      - name: Publish package
        working-directory: modules/plugin-postcss
        run: bunx jsr publish --allow-dirty

  publish-core:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Set up Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: master
      - name: Publish
        run: make publish
