name: Publish packages
on:
  push:
    branches:
      - master
jobs:
  publish-plugin-postcss:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        working-directory: modules/plugin-postcss
        run: bunx jsr add @lush/lush && bun install
      - name: Publish package
        working-directory: modules/plugin-postcss
        run: bunx jsr publish --allow-dirty

  publish-core:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v2
      - name: Set up Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: master
      - name: Build
        run: bazel build //...
      - name: Merge directories 1
        working-directory: modules/core
        run: mkdir -p /home/runner/work/lush/lush/build && cp -r package /home/runner/work/lush/lush/build/ && cp -r scripts /home/runner/work/lush/lush/build/package/ && cp README.md /home/runner/work/lush/lush/build/package/
      - name: Merge directories 2
        run: cp bazel-bin/modules/core/lush /home/runner/work/lush/lush/build/package/
      - name: Publish package
        working-directory: /home/runner/work/lush/lush/build/package
        run: bun x jsr publish --allow-dirty
