name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: modules/plugin-postcss
        run: bun install @types/bun

      - name: Publish package
        working-directory: modules/plugin-postcss
        run: bun x jsr publish
